image: node:latest

stages:
  - test
#    - build
#    - deploy
cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules/


test:
  stage: test

  script:
    - npm ci
    - npm test a

  tags: [test]
