image: node:latest

stages:
    - test  
#    - build
#    - deploy
cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths: 
  - node_modules/

before_script:
  - npm ci
test:
  stage: test

  script: 
    - npm test a
    
  tags: [test]
  


